@startuml
left to right direction
skinparam packageStyle rectangle
actor customer
actor canteen as "canteen website"
actor google as "google maps api"
rectangle Gahlia {
  customer -- (view weekly meal list)
  (view daily meal list)
  (view meal details)
  customer -- (show canteen location)
  (show canteen route)

  (view weekly meal list) .> (view daily meal list): include
  (view daily meal list) .> (view meal details): include
  (show canteen location) .> (show canteen route): include

  (view weekly meal list) -- canteen
  (show canteen location) -- google
}
@enduml

