@startuml
Title "show the canteen location"
start
:Open the App;
:Click on the Hamburger Menu;
:Click on the Maps button;
:Show the Map of Karlsruhe with canteen location marker;
floating note left
  uses google maps api
end note
stop
@enduml


