@startuml
Title "OCP Gahlia Heiarchy for React"
class	home {
 - hook1: "side menu"
 - hook2: "landing"
}
class	landing {
 - background: image
}
class	"side menu" {
 - hook: canteens
}
class	canteenlist {
 - hooks[]: canteen[]
}
class 	canteen {
 - hook1: weekdays
 - hook2: meallist
}
class	weekdays {
 - hooks[]: day[]
}
class	day {
 + gen-meal-items(weekday: Integer, mensa-id: Integer): meallist
}
class   meallist{
 - hooks[] : meal[]
}
class 	meal {
 - hook: details
 + gen-meal-details(self): details
}
class 	details {
 - details: image
}
class	maps {
 - hooks[]: marker[]
 - hook: route
}
class	marker {
 - mensa-locations[]: Float, Float
}
class	route {}
home o.. landing
home o.. "side menu"
"side menu" o.. canteenlist
canteenlist *.. canteen
canteen *.. meallist
canteen *.. weekdays
weekdays *.. day
meallist *.. meal
meal *.. details
"side menu" o.. maps
maps *.. marker
maps *.. route
home .. scrapercache
day .. meallist
class   scrapercache {
  - mensa-urls[] : String[]
  - dirtbag : struct
  - parsed : struct
  - cachepath : String

  - validate-cache(weekday: Integer, mensa-id: Integer) : boolean
  - read-cache(weekday: Integer, mensa-id: Integer) : boolean
  - write-cache() : boolean
  - pullparse(mensa-id) : void
  + gimme-data(weekday: Integer, mensa-id: Integer) : struct
}
@enduml
