@startuml
Title "Display Meal Details"

actor Alice
participant Gahlia
participant Cache as "Cache / Internet Resource"

Alice -> Gahlia: Open the App
activate Gahlia
Gahlia -> Cache: Retrieve canteen information
activate Cache
Cache --> Gahlia: done
deactivate Cache
Alice -> Gahlia: Click on the Hamburger Menu
Gahlia -> Gahlia: Show the canteen names
Gahlia --> Alice: done
deactivate Gahlia
Alice -> Gahlia: Select a canteen
activate Gahlia
Gahlia -> Cache: Load meal list
activate Cache
Cache --> Gahlia: done
deactivate Cache
Gahlia -> Gahlia: Show meal list
Gahlia --> Alice: done
deactivate Gahlia
Alice -> Gahlia: Select meal
activate Gahlia
Gahlia -> Cache: Load meal details
activate Cache
Cache --> Gahlia: done
deactivate Cache
Gahlia -> Gahlia: Show meal details
Gahlia --> Alice: done
deactivate Gahlia
@enduml
